apiVersion: batch/v1
kind: Job
metadata:
  name: db-check-job
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: check
        image: busybox
        command:
        - "sh"
        - "-c"
        - "echo 'Running db check to $DB_HOST...'; sleep 5; echo 'Connected!'"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_host
