apiVersion: batch/v1
kind: Job
metadata:
    name: db-migration-
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: never
      containers:
        - name: migration
          image: busybox
          command:
            - "sh"
            - "c"
            - "echo 'Running db migration...'; sleep 10; echo 'Done!'"
